/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package invoicegenerator;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankit Mishra
 */
public class allprint extends javax.swing.JFrame {

    /**
     * Creates new form allprint
     */
    DefaultTableModel dm=new DefaultTableModel();
    String col[]={"Bill No","Bill Date","Name","Contact No","Product Name","Quantity","Price","Ammount"};
    public allprint() {
        initComponents();
         setLocationRelativeTo(null);
         dm.setColumnIdentifiers(col);
         try{
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/INVOICE","root","");
       String query="select * from genretor";
       Statement st=conn.createStatement();
       st.execute(query);
       ResultSet rs=st.getResultSet();
       while(rs.next()){
       String a=rs.getString(2);
        String b=rs.getString(3);
         String c=rs.getString(4);
          String d=rs.getString(5);
           String e=rs.getString(6); 
           String f=rs.getString(7);
            String g=rs.getString(8);
              String h=rs.getString(9);
            dm.addRow(new Object[]{a,b,c,d,e,f,h,g});
       
       }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        jTable1.setModel(dm);
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jRadioButton1.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Single");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Traditional Arabic", 3, 18)); // NOI18N
        jRadioButton2.setText("Multipale");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jRadioButton1)
                .addGap(91, 91, 91)
                .addComponent(jRadioButton2))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jRadioButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         dispose();
         new Home().setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        int j=jTable1.getRowCount();
        for(int i=0;i<j;i++){
            
        dm.removeRow(0);
        
        }
         try{
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/INVOICE","root","");
       String query="select * from genretor";
       Statement st=conn.createStatement();
       st.execute(query);
       ResultSet rs=st.getResultSet();
       while(rs.next()){
       String a=rs.getString(2);
        String b=rs.getString(3);
         String c=rs.getString(4);
          String d=rs.getString(5);
           String e=rs.getString(6); 
           String f=rs.getString(7);
            String g=rs.getString(8);
              String h=rs.getString(9);
            dm.addRow(new Object[]{a,b,c,d,e,f,h,g});
       
       }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        jTable1.setModel(dm);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        int j=jTable1.getRowCount();
        for(int i=0;i<j-1;i++){
        dm.removeRow(0);
        
        }
         try{
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/INVOICE","root","");
       String query="select * from genretormltipleu";
       Statement st=conn.createStatement();
       st.execute(query);
       ResultSet rs=st.getResultSet();
       while(rs.next()){
       String a=rs.getString(2);
        String b=rs.getString(3);
         String c=rs.getString(4);
          String d=rs.getString(5);
           String e=rs.getString(6); 
           String f=rs.getString(7);
            String g=rs.getString(8);
              String h=rs.getString(9);
            dm.addRow(new Object[]{a,b,c,d,e,f,h,g});
       
       }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        jTable1.setModel(dm);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allprint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new allprint().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
